// pages/login.tsx
import React, {useState} from "react"
import Head from "next/head"

import {auth} from "../logic/firebase-client"

export default function Login() {

  const [email, setEmail]       = useState('')
  const [password, setPassword] = useState('')

  const doLogin = async (event: React.MouseEvent<HTMLButtonElement>): Promise<void> => {
    event.preventDefault()

    console.log('asdf')

    const result  = await auth.signInWithEmailAndPassword(email, password)
    const token   = await result.user.getIdToken()

    console.log('done')
  }

  return (
    <div>
      <Head>
        <title>maoo | Login</title>
      </Head>
      <h1>Login</h1>

      <form>
        <label>
          e-mail <input type='email' value={email} onChange={e => setEmail(e.target.value)}/>
        </label>
        <label>
          password <input type='password' value={password} onChange={e => setPassword(e.target.value)}/>
        </label>
        <button onClick={doLogin}>login</button>
      </form>
    </div>
  )
}

// src/pages/login.svelte
<div class="login">
  <h2>Login to maoo</h2>
  <button on:click={goBack}>Go Back</button>
  <br/>
  <br/>
  <form>
    <label>
      email
      <input type=email bind:value={email}>
    </label>
    <br/>
    <label>
      password
      <input type=password bind:value={password}>
    </label>
    <button on:click|preventDefault={doLogin}>Login</button>
  </form>
</div>
<script lang="ts">

  import {state}  from '../store/navigation'
  import {auth}   from '../logic/firebase'

  let email     : String
  let password  : String

  const doLogin = async () => {
    try {
      await auth.signInWithEmailAndPassword(email, password)

    } catch(error) {
      console.error(error)
    }
  }
  const goBack  = () => { $state.page = 'landing' }
</script>
